server.port=7070
#optional if Eureka server is running on port 8761
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#Configure the routes for different microservices (inventory ) 
spring.cloud.gateway.server.webflux.routes[0].id=id1
spring.cloud.gateway.server.webflux.routes[0].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/inventory/**

#Configure the routes for different microservices (order ) 
spring.cloud.gateway.server.webflux.routes[1].id=id2
spring.cloud.gateway.server.webflux.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**

