#DB config for Inventory MS
spring.datasource.url=jdbc:mysql://localhost:3306/inventory_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password={cipher}4c7b5913a06306551105c04a6a715c1a8e9cb15f1e1826d2573e268f19588574
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#contact info in case of issues
inventory.message=Welcome To Inventory Service
inventory.contactDetails.name=Riya Pathak
inventory.contactDetails.email=riya123@gmail.com
inventory.onCallSupport[0]=9123456678
inventory.onCallSupport[1]=9123456679
# Expose ALL actuator endpoints over HTTP (actually required is refresh)
management.endpoints.web.exposure.include=*
