#contact info in case of issues
inventory.message=Welcome To Inventory QA Micro 12345 Service
inventory.contactDetails.name=Mihir Sen 1
inventory.contactDetails.email=mihir123@gmail.com
inventory.onCallSupport[0]=9223456677
inventory.onCallSupport[1]=9323456679
# Expose ALL actuator endpoints over HTTP (actually required is refresh)
#management.endpoints.web.exposure.include=*
