# server port 
server.port=9090

#Eureka client props 
#optional if Eureka server is running on port 8761
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#required
eureka.instance.prefer-ip-address=true


#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#custom prop stock checking URL of inventory
#order.stock.check=http://localhost:8080/inventory/check/{skuCode}/{qty}
#custom property
#stock.check.url=http://inventory-service/inventory/check/{sku_code}/{quantity}
#spring.cloud.openfeign.okhttp.enabled=true
# For adding a binding in RabbitMq
spring.cloud.stream.default.group=order

#contact info in case of issues
order.message=Welcome To Order 12345 MicroService
order.contactDetails.name=Anish Sethi 2
order.contactDetails.email=anish@gmail.com
order.onCallSupport[0]=9173456677
order.onCallSupport[1]=9183456679

# Expose ALL actuator endpoints over HTTP (actually required is refresh)
#management.endpoints.web.exposure.include=*

 

